# Generated by Django 4.1 on 2022-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confrimed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confrimed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], max_length=100),
        ),
    ]
