# Generated by Django 4.1 on 2022-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_monthly_sales_report_sales_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='img4',
            field=models.ImageField(default=True, upload_to='static'),
        ),
    ]
