# Generated by Django 4.1 on 2022-09-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_produc_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='c_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produc',
            name='p_offer',
            field=models.BooleanField(default=False),
        ),
    ]
