# Generated by Django 4.1 on 2022-10-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_produc_c_offer_produc_p_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='o_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
