# Generated by Django 4.1 on 2022-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_produc_o_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produc',
            name='o_percentage',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
