# Generated by Django 4.1 on 2022-10-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
