# Generated by Django 4.1 on 2022-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_alter_customer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
